-- Snowflake objects are created automatically by the app, but here are the definitions:
CREATE TABLE IF NOT EXISTS RUBRICS (
  ID STRING DEFAULT UUID_STRING(),
  NAME STRING,
  CRITERIA VARIANT,
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS STUDENT_SUBMISSIONS (
  ID STRING DEFAULT UUID_STRING(),
  TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  STUDENT_ID STRING,
  COURSE STRING,
  LANGUAGE STRING,
  CODE STRING,
  RUBRIC_NAME STRING,
  TOTAL_SCORE FLOAT,
  AI_MODEL STRING,
  FEEDBACK VARIANT
);